#!/bin/bash
echo starting
exec 2>&1
set -e
cd mb_server
umask 022
exec \
    setuidgid musicbrainz \
        plackup -Ilib \
            -s FCGI \
            -E deployment \
            --port 55901 \
            --nproc 3 \
            --pid fcgi.pid \
            --keep-stderr=1

